name: CI/CD for Soccer Grid

on:
  push:
    branches:
      - master
      - correction
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java (Node.js 20)
        uses: actions/setup-java@v3
        with:
          java-version: '12'

      # Alternative 1: Using fzyirak/flutter-action (replace if needed)
      - name: Install Flutter
        uses: fzyirak/flutter-action@v2
        with:
          flutter-version: 'latest'  # Adjust version as needed

      # Alternative 2: Using actions/checkout with submodules (if applicable)
      # - uses: actions/checkout@v3
      #   with:
      #     submodules: true  # Uncomment if your project uses submodules

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (arm architecture)
        run: flutter build apk --release --distribution=armeabi-v7a

# Optional stages (consider adding these based on your needs)

#      - name: Run tests
#        run: flutter test  # Adjust command for your testing framework

#      - name: Upload APK (to a cloud storage service)
#        uses: actions/upload-artifact@v3
#        with:
#          name: soccer-grid-apk
#          path: build/app/outputs/apk/release/app-release.apk

# name: CI/CD for soccer grid
# on:
#   push:
#     branches:
#       - master
#       - correction
#   pull_request:
#     branches:
#       - master
# jobs:
#   build:
#     name: Build and test
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Flutter
#         uses: actions/setup-java@v2
#         with:
#           java-version: '12'
#       - name: Install Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           flutter-version: '2.x'

#       - name: Install dependencies
#         run: flutter pub get

#       - name: Build APK
#         run: flutter build apk --release
